### ISSUE TITLE
puTTY vs kiTTY  ...

### ISSUE THREAD

**Issue by berryamin** [trimstray/the-book-of-secret-knowledge#100]
kiTTY is a huge improvement over puTTY ... shall we put it along with putty or simply replace putty with putty ?

http://www.9bis.net/kitty/#!index.md

it brings all the features of puTTY and a lot more features like:
 - Auto reconnect of disconnected session
 - Automatic command after specified time at login
 - Running a locally saved script on a remote session
 - "Always visible" option for selected session (like vlc "Float on Top")
 - Window transparency

Bonus:
 - Hidden Editor (to include/prepare some text before sending to terminal window)

**Comment by boltomli** [comment]
Does kiTTY have replacement for plink? If so it can replace putty. But if not, plink is the reason putty is necessary.

**Comment by trimstray** [comment]
@berryamin :

Both are great, kitty is on this list (see [Terminal emulators](https://github.com/trimstray/the-book-of-secret-knowledge#black_small_square-terminal-emulators)).

**Comment by berryamin** [comment]
Oki I see.
Question asked on kitty forum, let's see what happens.
https://github.com/cyd01/KiTTY/issues/46
