### ISSUE TITLE
Micro as a cross platform cli text editor

### ISSUE THREAD

**Issue by StewAlexanderACC** [trimstray/the-book-of-secret-knowledge#107]
[Micro Text Editor](https://micro-editor.github.io/) - cross platform minimal terminal / CLI text editor that humbly I think should be on your list of editors ...

VIm like syntax highlighting, good for those who don't use Vim enough to be good with it, multiple tabs, decent set of commands and an inline help similar to that of LNAV

Sort of like nano but with themes.

**Comment by trimstray** [comment]
It looks really interesting. Added. Thanks.
