### ISSUE TITLE
Make authoring the readme file enjoyable again

### ISSUE THREAD

**Issue by MartinMuzatko** [trimstray/the-book-of-secret-knowledge#12]
Hey. I recently wanted to add my few points to the list. Editing and authoring the readme file is painful. Do you really require the red diamonds everywhere? Would a bulleted list also do it just fine?

If wanted, I'd come up with a suggestion/PR.

**Comment by trimstray** [comment]
Hi @MartinMuzatko!

All suggestions/PR are welcome!

A few simple rules for this project:

- inviting and clear
- not tiring
- useful

These below rules may be better, I know about it:

- easy to contribute to
- easy to find (TOC)

If the authoring is exhausting for you, you can add [Issue](https://github.com/trimstray/the-book-of-secret-knowledge/issues)

I'm waiting for Your suggestions!

**Comment by trimstray** [comment]
I consider it unnecessary.
