### ISSUE TITLE
RSS Feed of new items

### ISSUE THREAD

**Issue by lbonanomi** [trimstray/the-book-of-secret-knowledge#126]
Love watching this project grow!

Are there plans for advertising changes? I got tired of reading raw commit logs and whacked-together an [RSS feed](https://lbonanomi.github.io/BoSK-Watch/feed.xml) of additions, but it's pretty-raw.

**Comment by RealOrangeOne** [comment]
Fancy!

GitHub exposes an ATOM feed of the commits, which may also be useful

https://github.com/trimstray/the-book-of-secret-knowledge/commits.atom

**Comment by lbonanomi** [comment]
You're absolutely right! The ATOM feed is the backbone of this thing, I'm just dressing it up with data from the commit's patch-sets.

**Comment by trimstray** [comment]
It's a great idea!

**Comment by HumanG33k** [comment]
and or make release and be notify by email with watch release notification ?

**Comment by trimstray** [comment]
I added [RSS Feed & Updates](https://github.com/trimstray/the-book-of-secret-knowledge#newspaper-rss-feed--updates) chapter.
