### ISSUE TITLE
Add z under "Files and directories"

### ISSUE THREAD

**Issue by gbalduzzi** [trimstray/the-book-of-secret-knowledge#137]
[z](https://github.com/rupa/z) is a simple command that tracks the folder you use the most and allow you to jump, without having to type the whole path.

For example, if you want to navigate to the previously-visited folder `/home/user/projects/apps/android-app`, instead of

```
cd /home/user/projects/apps/android-app
cd ~/projects/apps/android-app
```
 you can simply
```
z android-app
```

I think it would be a nice addition in the "Files and directories" section

**Comment by trimstray** [comment]
Hi!

I added `Shell plugins` section.
