### ISSUE TITLE
Adding securitynewsletter.co to "Your daily knowledge and news"?

### ISSUE THREAD

**Issue by dietervds** [trimstray/the-book-of-secret-knowledge#24]
Thanks for building an amazing list like this!

I didn't see a section for relevant newsletters, but I'd love to suggest the one I write on [infosec news](https://securitynewsletter.co/). If it's deemed useful and appropriate, it'd be an honor to be part of the list. 
 
(Something along the lines of:)
```
&nbsp;&nbsp;:small_orange_diamond: <a href="https://securitynewsletter.co/"><b>securitynewsletter.co</b></a> - security news as a weekly digest.<br>
```

**Comment by trimstray** [comment]
Hi @dietervds!

Your project is amazing!

This repository has `Your daily knowledge and news` chapter :)

Sum up: I added https://securitynewsletter.co to this project.

Thank you very much!

**Comment by dietervds** [comment]
Thank you! :-)
