### ISSUE TITLE
Two people and easy 

### ISSUE THREAD

**Issue by qezZxxcd** [trimstray/the-book-of-secret-knowledge#256]

**Comment by qezZxxcd** [comment]
@qezZxxcd

**Comment by traceylademan** [comment]
- [ ] I **![image](https://user-images.githubusercontent.com/59878225/140792823-74f919dc-862e-4523-b280-f12ea7a9bcb7.jpeg)**

**Comment by KOLANICH** [comment]
@trimsray, could you just block all of them?

**Comment by trimstray** [comment]
@KOLANICH I blocked both. Unfortunately, Github is full of this type of junk.
