### ISSUE TITLE
LastPass for Password Manager

### ISSUE THREAD

**Issue by lalaithan** [trimstray/the-book-of-secret-knowledge#27]
[LastPass](https://www.lastpass.com/) is a popular password manager.

**Comment by shmink** [comment]
I've been using this for a few months now. Personally, think it's one of the better ones out of there. Even beats the paid 1password that I use at work.

**Comment by trimstray** [comment]
Hi guys!

I have never used LastPass but I have heard a lot of good about it.

I have questions:

- what if we lose access to the network? we lose access to the manager?
- how about the security of LastPass?

**Comment by shmink** [comment]
> what if we lose access to the network? we lose access to the manager?

At least on the mobile app. There is a log in offline mode. Testing it now on the firefox extension at least I see no such option. But likely if one is using their browser internet access is assured. Also just checked [their download page](https://lastpass.com/misc_download2.php) and there is an option for a program which I assume to have in the login offline option.

> how about the security of LastPass?

For this, I suppose it's a _your mileage may vary_ situation. As [the following article](https://lifehacker.com/is-lastpass-secure-what-happens-if-it-gets-hacked-1555511389) mentions they are a business focused entirely on security so more likely than others to be up to date on the best practices.

The other password managers I've tried in the past are the previously mentioned 1password which is paid and has the benefit of multiple users sharing the same password _vault_ (why I use it at work) this is however a paid service. The other free one I've used is Dashlane, also as an extension. I found Dashlane to be cumbersome and annoying how it seems to pop up in unnescary scenario as well as occasionally taking control of forms and deciding it knows best.

**Comment by trimstray** [comment]
> Lastpass runs in the browser, right at the point of the spear of most malware. If there is a browser bug that allows data to leak between tabs, you're hosed.

> Also, the company itself has had at least three intrusions (that they've reported). They vaults are layered encryption, but it at least demonstrates they're a high profile target and they have trouble with security.

From: [https://www.reddit.com/r/privacy/comments/6erbc7/keepass_vs_lastpass/](https://www.reddit.com/r/privacy/comments/6erbc7/keepass_vs_lastpass/)

I'm not saying no, but I'm going to think about it, okay? At the moment I'm adding [enpass](https://www.enpass.io/):

- totally free desktop version
- saves your data locally on device
- also contain cloud function (if you want)

**Comment by trimstray** [comment]
Commit: ddd3535
