### ISSUE TITLE
Am I being hacked?

### ISSUE THREAD

**Issue by dmcnasty517** [trimstray/the-book-of-secret-knowledge#270]
![Screenshot_20211112-060538_File Manager +.jpg](https://user-images.githubusercontent.com/35431959/141467428-553104dc-efd4-411b-a4e8-baf39c205e0e.jpg)
[]![Screenshot_20211112-061612_File Manager +.jpg](https://user-images.githubusercontent.com/35431959/141467530-c6be5ce1-3c1d-4038-b02c-b94c12266aa4.jpg)

**Comment by KOLANICH** [comment]
It is unclear.

**Comment by dmcnasty517** [comment]
How can I find out? Full bug report?

DM

**Comment by Yommyjay222** [comment]
Am here what log are they

**Comment by dmcnasty517** [comment]
Bug report from phone I think. I got lots more if you wanna jump down a
rabbit hole with me
