### ISSUE TITLE
Full bug report. Am I being Hacked? 

### ISSUE THREAD

**Issue by dmcnasty517** [trimstray/the-book-of-secret-knowledge#276]

**Comment by bn70902** [comment]
Bug report summary:

----->Info: id=1 pid=8355 dry_run=0 args=/system/bin/dumpstate -d -p -B -z -o 
/data/user_de/0/com.android.shell/files/bugreports/bugreport extra_options=

The second part could be explaining the issue.

----->restart_on_corruption ignore_zero_blocks use_Dec from_device#................

In the bugreport it speaks a lot about Facebook.Katana. 
Example: facebook.rtc.activities.InCallActivity#0] 409.36 0.046 0.997 0.003 [com.facebook.katana/com.facebook.photos.pandora.ui.PandoraTabPagerActivity. 

I am learning cyber security so I am fascinated with solving these issues. I know how to navigate and find the issue. Sometimes I can fix the issue but I am trying to figure out who caused the issue. I never click on a shady link that gets sent to me so I do not know how this bug could've got there. 
I thought I should ask an expert and get some insight. I am new on github.com

Thanks for your time.
Sincerely Blake Nelson

**Comment by matiasjoey** [comment]
Hello Blake, thank you for helping me. I appreciate it. I have no idea
what's going on with my phone. But there is one thing I know, I've been
hacked and don't know what to do! If you could please stay in contact with
me that would be great. I'm new to git hub and pretty much have no idea how
to go about what to do. I have no computer skills, meaning I can't code or
hack and have a hard time understanding things. I'm on a cell phone trying
to learn how to stop whoever is hacking me.

Thank you very much! Joey

I Invented Murder
