### ISSUE TITLE
Suggestion: Add CliFM

### ISSUE THREAD

**Issue by leo-arch** [trimstray/the-book-of-secret-knowledge#293]
[CliFM](https://github.com/leo-arch/clifm) is a file manager with a unique approach: unlike most file managers out there, based on some kind of TUI, CliFM is entirely based on the command line.

**Comment by 7565A** [comment]
> [CliFM](https://github.com/leo-arch/clifm) is a file manager with a unique approach: unlike most file managers out there, based on some kind of TUI, CliFM is entirely based on the command line.
