### ISSUE TITLE
- hello- world

### ISSUE THREAD

**Issue by Harister** [trimstray/the-book-of-secret-knowledge#298]
> [](VK bot)

**Comment by Getahunmelku** [comment]
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

   <meta name="language" content="EN"/>
<meta name="robots" content="index, follow"/>


    <title>ZAK</title>

    
    <script src="https://www.zakclinic.com/covid/js/app.js" defer></script>
    
    
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    
    <link href="https://www.zakclinic.com/covid/css/app.css" rel="stylesheet">
</head>
<body>
    <div id="app">
        <ul class="nav py-3">

    </ul>


<nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="https://www.zakclinic.com/covid">

                    SEBEZ LIS Web 1.0
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    
                    <ul class="navbar-nav mr-auto">












                        <li class="nav-item">
                          <a class="nav-link" href="https://www.zakclinic.com/covid/labClients">Laboratory Clients</a>
                        </li>
                      
                    </ul>

                    
                    <ul class="navbar-nav ml-auto">
                        
                                                    <li class="nav-item">
                                <a class="nav-link" href="https://www.zakclinic.com/covid/login">Login</a>
                            </li>
                            
                                                                        </ul>
                </div>
            </div>
        </nav>
        <main class="py-4">
        <div class="container">
            <link href="https://www.zakclinic.com/covid/css/styles.css" rel="stylesheet" type="text/css" >
<div class="">
    <div>
        <img src="https://www.zakclinic.com/covid/img/header.jpg" alt="" width=100%>
    </div>
    <div class="myheader" style="background-color: lightblue;">
        Client Information
    </div>
                <div class="row" width="100%" style="padding: 0px 5px 5px 5px;">
                <div class="col">
                    <div class="spanMargine">
                        <span class="thik">Full Name: </span> <span>MESERT BARKELEGN SEBACHE</span>
                    </div>
                    <div class="spanMargine">
                        <span class="thik">Age in year: </span> <span>30</span>
                    </div>
                    <div  class="spanMargine">
                        <span class="thik">Nationality: </span> <span>Ethiopian</span>
                    </div>
                    <div class="spanMargine">
                        <span class="thik">Phone Number: </span> <span>0910452471</span>
                    </div>
                    <div class="spanMargine">
                        <span class="thik">Residence City/Town: </span> <span>AWASA</span>
                    </div>

                </div>
                <div class="col">
                    <div class="spanMargine">
                        <span class="thik">Sex: </span> <span>Female</span>
                    </div>
                    <div class="spanMargine">
                        <span class="thik">Passport Number: </span> <span>EP4567890</span>
                    </div>
                    <div class="spanMargine">
                        <span class="thik">Region: </span> <span>SOUTH</span>
                    </div>
                </div>
            </div>
                

    <div class="myheader" style="background-color: lightblue;">
        Specimen Information
    </div>
        <div class="rows"  style="margin: 5px 5px 5px 5px;">
            <div class="column">
                <div class="spanMargine">
                    <span class="thik">Specimen Id: </span> <span>21226366606</span>
                </div>
                <div class="spanMargine">
                    <span class="thik">Date of Specimen Collection: </span> <span>2021-12-22</span>
                </div>
                <div class="spanMargine">
                    <span class="thik">Site of Specimen Collection: </span> <span>ZAK INTERNAL MEDICINE SPECIALITY CLINIC</span>
                </div>
                <div class="spanMargine">
                    <span class="thik">Sample Collected By: </span> <span>Mahfuz Abebe</span>
                </div>


            </div>
            <div class="column">
                <div class="spanMargine">
                    <span class="thik">Specimen Type: </span> <span>Nasopharyngeal &amp; Oropharyngeal Swab</span>
                </div>
                <div class="spanMargine">
                    <span class="thik">Time of Specimen Collection: </span> <span>15:56:00</span>
                </div>
                <div class="spanMargine">
                    <span class="thik">Specimen Quality: </span> <span>Accepted</span>
                </div>
                <div class="spanMargine">
                    <span class="thik">Requested By: </span> <span>Self Request</span>
                </div>
            </div>
        </div>
    <div class="myheader" style="background-color: lightblue;">
        Test Result
    </div>
        <div class="rows"  style="margin: 5px 5px 5px 5px;">
            <div class="column">
                <div class="spanMargine">
                    <span class="thik">Requested Test: </span> <span>SARS-COV-2</span>
                </div>
                <div class="spanMargine">
                    <span class="thik">Test Method: </span> <span>RT-PCR</span>
                </div>
                <div class="spanMargine">
                    <span class="thik">RT-PCR test: </span> <span>Negative</span>
                </div>
                <div class="spanMargine">
                    <span class="thik">Date Result Issued: </span> <span>2021-12-22</span>
                </div>
                <div class="spanMargine">
                    <span class="thik">Test Done By: </span> <span>Belete Woldesemayat</span>
                </div>
                <div class="spanMargine">
                    <span class="thik">Testing Laboratory: </span>
                    <span>ZAK INTERNAL MEDICINE SPECIALITY CLINIC</span>
                </div>
                <div class="spanMargine">
                    <span class="thik">Report Authorized and Issued by: </span> <span>Dr Zakaria Abdulhamid</span>
                </div>
                
            </div>
            <div class="column">
                <div class="spanMargine">
                    <span class="thik">Test protocol/SOP No and Title: </span> <span>SARS-CoV-2 Testing</span>
                </div>
                <div style="">

                </div>
                
                <p>&nbsp;</p>
                
                <div class="spanMargine">
                    <span class="thik">SARS-CoV-2  IgM test: </span> <span></span>
                </div>
                <div class="spanMargine">
                    <span class="thik">Time Result Issued: </span> <span>23:00:00</span>
                </div>
                <div class="spanMargine">
                    <span class="thik">Result Reviewed by: </span> <span>Mengistu Yimer</span>
                </div>
                  <div style="">
                                     <?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="100" height="100" viewBox="0 0 100 100"><rect x="0" y="0" width="100" height="100" fill="#ffffff"/><g transform="scale(3.03)"><g transform="translate(0,0)"><path fill-rule="evenodd" d="M9 0L9 1L8 1L8 2L9 2L9 3L8 3L8 4L10 4L10 7L11 7L11 4L12 4L12 5L13 5L13 6L12 6L12 9L13 9L13 8L14 8L14 9L16 9L16 10L15 10L15 11L14 11L14 12L16 12L16 11L17 11L17 9L18 9L18 8L17 8L17 6L16 6L16 5L17 5L17 4L18 4L18 3L19 3L19 2L18 2L18 3L17 3L17 4L16 4L16 2L17 2L17 0L16 0L16 1L15 1L15 0L13 0L13 1L11 1L11 2L10 2L10 0ZM19 0L19 1L22 1L22 2L20 2L20 3L22 3L22 4L23 4L23 5L24 5L24 4L25 4L25 3L24 3L24 2L23 2L23 1L24 1L24 0ZM13 1L13 2L12 2L12 4L14 4L14 5L16 5L16 4L15 4L15 3L14 3L14 2L15 2L15 1ZM22 2L22 3L23 3L23 2ZM10 3L10 4L11 4L11 3ZM19 4L19 5L18 5L18 7L19 7L19 10L20 10L20 11L19 11L19 12L20 12L20 13L16 13L16 14L15 14L15 13L12 13L12 11L13 11L13 10L11 10L11 11L10 11L10 9L11 9L11 8L6 8L6 9L7 9L7 10L6 10L6 11L5 11L5 8L0 8L0 9L1 9L1 10L2 10L2 11L0 11L0 12L2 12L2 15L0 15L0 17L1 17L1 18L2 18L2 17L4 17L4 16L5 16L5 18L4 18L4 21L3 21L3 20L2 20L2 22L5 22L5 23L2 23L2 25L3 25L3 24L5 24L5 25L8 25L8 27L9 27L9 28L8 28L8 33L10 33L10 32L11 32L11 29L12 29L12 30L13 30L13 31L12 31L12 33L13 33L13 32L14 32L14 33L15 33L15 32L14 32L14 31L16 31L16 30L15 30L15 29L12 29L12 27L13 27L13 26L11 26L11 29L9 29L9 28L10 28L10 24L11 24L11 23L10 23L10 22L11 22L11 21L12 21L12 22L13 22L13 23L12 23L12 25L13 25L13 24L14 24L14 25L16 25L16 26L15 26L15 27L14 27L14 28L15 28L15 27L16 27L16 28L17 28L17 29L19 29L19 30L17 30L17 31L19 31L19 30L22 30L22 29L23 29L23 28L24 28L24 29L25 29L25 30L26 30L26 31L27 31L27 32L24 32L24 33L27 33L27 32L28 32L28 33L29 33L29 31L30 31L30 32L31 32L31 33L32 33L32 32L31 32L31 31L30 31L30 30L33 30L33 28L31 28L31 27L32 27L32 26L33 26L33 24L32 24L32 26L31 26L31 25L30 25L30 24L31 24L31 23L32 23L32 22L33 22L33 21L32 21L32 20L31 20L31 19L32 19L32 18L33 18L33 17L32 17L32 16L31 16L31 15L32 15L32 14L33 14L33 13L31 13L31 15L30 15L30 13L29 13L29 12L28 12L28 11L29 11L29 10L28 10L28 11L27 11L27 9L28 9L28 8L27 8L27 9L26 9L26 8L25 8L25 6L24 6L24 7L23 7L23 6L22 6L22 5L21 5L21 4ZM8 5L8 7L9 7L9 5ZM19 5L19 7L20 7L20 5ZM13 6L13 7L14 7L14 8L16 8L16 9L17 9L17 8L16 8L16 6L15 6L15 7L14 7L14 6ZM21 6L21 7L22 7L22 6ZM20 8L20 10L21 10L21 9L22 9L22 10L23 10L23 11L22 11L22 12L21 12L21 11L20 11L20 12L21 12L21 14L18 14L18 15L17 15L17 14L16 14L16 15L14 15L14 16L13 16L13 17L12 17L12 15L13 15L13 14L12 14L12 13L11 13L11 12L10 12L10 13L11 13L11 18L13 18L13 19L12 19L12 21L15 21L15 22L16 22L16 23L14 23L14 24L16 24L16 23L17 23L17 24L18 24L18 25L17 25L17 28L18 28L18 26L19 26L19 28L20 28L20 29L21 29L21 27L22 27L22 28L23 28L23 26L24 26L24 24L23 24L23 25L22 25L22 24L20 24L20 22L19 22L19 21L17 21L17 20L19 20L19 19L21 19L21 18L23 18L23 19L22 19L22 20L20 20L20 21L22 21L22 23L26 23L26 24L27 24L27 23L26 23L26 21L27 21L27 22L29 22L29 21L27 21L27 20L26 20L26 19L25 19L25 18L26 18L26 17L27 17L27 19L28 19L28 20L29 20L29 17L30 17L30 19L31 19L31 16L30 16L30 15L29 15L29 17L27 17L27 15L28 15L28 14L29 14L29 13L27 13L27 11L25 11L25 10L26 10L26 9L24 9L24 8L23 8L23 9L22 9L22 8ZM29 8L29 9L30 9L30 8ZM31 8L31 10L33 10L33 9L32 9L32 8ZM23 9L23 10L24 10L24 9ZM3 10L3 11L4 11L4 10ZM8 10L8 12L7 12L7 11L6 11L6 12L3 12L3 14L4 14L4 15L5 15L5 16L7 16L7 17L6 17L6 18L5 18L5 19L6 19L6 20L8 20L8 19L6 19L6 18L8 18L8 16L9 16L9 17L10 17L10 14L9 14L9 15L8 15L8 16L7 16L7 15L5 15L5 14L7 14L7 13L9 13L9 10ZM23 11L23 14L22 14L22 15L20 15L20 17L19 17L19 18L21 18L21 16L22 16L22 17L23 17L23 18L24 18L24 17L26 17L26 15L27 15L27 13L26 13L26 12L24 12L24 11ZM30 11L30 12L31 12L31 11ZM6 12L6 13L7 13L7 12ZM25 13L25 14L23 14L23 16L25 16L25 15L26 15L26 13ZM2 15L2 16L3 16L3 15ZM18 15L18 16L19 16L19 15ZM14 16L14 17L16 17L16 18L15 18L15 19L14 19L14 20L15 20L15 21L16 21L16 22L17 22L17 21L16 21L16 20L17 20L17 16ZM9 18L9 22L10 22L10 20L11 20L11 19L10 19L10 18ZM23 19L23 20L22 20L22 21L23 21L23 22L24 22L24 21L26 21L26 20L24 20L24 19ZM0 20L0 25L1 25L1 20ZM30 20L30 21L31 21L31 20ZM6 21L6 22L8 22L8 21ZM30 22L30 23L31 23L31 22ZM5 23L5 24L7 24L7 23ZM8 23L8 25L9 25L9 23ZM18 23L18 24L19 24L19 23ZM19 25L19 26L20 26L20 27L21 27L21 26L22 26L22 25ZM25 25L25 28L28 28L28 25ZM26 26L26 27L27 27L27 26ZM30 26L30 27L31 27L31 26ZM30 28L30 29L31 29L31 28ZM26 29L26 30L27 30L27 31L29 31L29 30L28 30L28 29ZM9 30L9 31L10 31L10 30ZM23 30L23 31L20 31L20 32L19 32L19 33L20 33L20 32L22 32L22 33L23 33L23 31L24 31L24 30ZM16 32L16 33L18 33L18 32ZM0 0L0 7L7 7L7 0ZM1 1L1 6L6 6L6 1ZM2 2L2 5L5 5L5 2ZM26 0L26 7L33 7L33 0ZM27 1L27 6L32 6L32 1ZM28 2L28 5L31 5L31 2ZM0 26L0 33L7 33L7 26ZM1 27L1 32L6 32L6 27ZM2 28L2 31L5 31L5 28Z" fill="#000000"/></g></g></svg>

                                
                </div>
            </div>
        </div>
        <div style="text-align: center;">


            <div class="spanMargine">
                <span class="middle"><span class="thik">Signature: </span> 
                
                                <span><img src="https://www.zakclinic.com/covid/img/signature.jpg" alt="" width=100px height=70px> </span></span>
                            </div>
            <div class="spanMargine">
                <span class="middle"><span class="thik">Date: </span> <span>2021-12-22</span></span>
            </div>


        </div>
    <div class="myheader" style="height:35px; box-shadow: 10px 10px 5px grey;">
    </div>
    <div style="padding: 15px 0px 15px 0px;">
        <img src="https://www.zakclinic.com/covid/img/footer.png" alt="" width=100%>
    </div>
    
    <div style="padding: 10px 0px 10px 0px;">
        <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOAAAAAeAQMAAAAPe4DLAAAABlBMVEX///8AAABVwtN+AAAAAXRSTlMAQObYZgAAAAlwSFlzAAAOxAAADsQBlSsOGwAAADBJREFUKJFj+Mx/+Pxhfv4zxvwMhxk+f/5z5r+9jb3BHxvjA3/OM4xKjkqOSlIuCQDDZbzKUonVqgAAAABJRU5ErkJggg==" alt=""  class="middle">
    </div>
    <div style="padding: 10px 0px 10px 0px;">
        

        
    </div>

</div>
        </div>
        </main>
    </div>
</body>
<script src="https://www.zakclinic.com/covid/js/app.js"></script>
</html>

**Comment by Getahunmelku** [comment]
![IMG_20211222_144154.jpg](https://user-images.githubusercontent.com/93838930/147087627-7baeba3d-bcf1-4529-83dc-32349265699d.jpg)
