### ISSUE TITLE
 I'm confused. 

### ISSUE THREAD

**Issue by CHASMEN89** [trimstray/the-book-of-secret-knowledge#306]
Can someone please help figure out what this is for? And if its the reason why I feel like I'm going insane...because it seems like everyone around knows what's going on, but I'm still in the dark. Depressing.

**Comment by TheTechRobo** [comment]
> A collection of inspiring lists, manuals, cheatsheets, blogs, hacks, one-liners, cli/web tools and more.

What are you confused about?

**Comment by KOLANICH** [comment]
Reported him to GH support. I hope they will help him.
