### ISSUE TITLE
Security of 3des

### ISSUE THREAD

**Issue by remyabel** [trimstray/the-book-of-secret-knowledge#34]
OpenSSL doesn't include [3des by default](https://www.openssl.org/blog/blog/2016/08/24/sweet32/) and considers it a weak cipher. Many Linux distros add `enable-weak-ssl-ciphers` for compatibility anyway, but I still don't think it should be encouraged. I'm not an expert, as I see 3des used a lot for encrypting the private key when generating self-signed certificates. Perhaps it would be better to change it to this:

```diff
diff --git a/README.md b/README.md
index 4704183..f5686bb 100644
--- a/README.md
+++ b/README.md
@@ -1289,8 +1289,8 @@ openssl s_client -cipher 'AES128-SHA' -connect google.com:443
 ###### Generate private key

```bash
-# _ciph: des3, aes
-( _ciph="des3" ; _fd="private.key" ; _len="2048" ; \
+# _ciph: des3, aes128
+( _ciph="aes128" ; _fd="private.key" ; _len="4096" ; \
 openssl genrsa -${_ciph} -out ${_fd} ${_len} )
 ```

*N.B.*: older versions of OpenSSL only support des, 3des and idea, but if somebody is using an OpenSSL that old they got bigger problems.

**Comment by remyabel** [comment]
> Which default encryption does OpenSSL use? We pass only genrsa and output file.

If you specify nothing, it uses no encryption. So that's no good.

**Comment by trimstray** [comment]
Ohh... yes it's obvious :1st_place_medal: for me haha

Fixed.

Also good about key length: [RSA Key Sizes: 2048 or 4096 bits?](https://danielpocock.com/rsa-key-sizes-2048-or-4096-bits)
