### ISSUE TITLE
Engineer AutoCAD DRW IMAGe

### ISSUE THREAD

**Issue by AnonMoon** [trimstray/the-book-of-secret-knowledge#344]
Lost Transmission - Mechanical Engineer Wanted
![image](https://user-images.githubusercontent.com/97193619/154902424-301a076d-5970-440a-ac6c-5f5d77c64b32.jpeg)
..
![image](https://user-images.githubusercontent.com/97193619/154902455-d108c1ef-2945-4580-835f-edcbcbc935ca.jpeg)
..
![image](https://user-images.githubusercontent.com/97193619/154902538-e4ab2ff8-7b7c-423e-9fa6-d2bac8f3341a.jpeg)

**Comment by AnonMoon** [comment]
صـباح النور .. 1050

**Comment by AnonMoon** [comment]
- - - - - 
- [ ] /سلام
- [ ] مرحبًا
- [ ] استيقظ
- [ ] اليوم

**Comment by Sleekbobby1011** [comment]
What platform?

**Comment by AnonMoon** [comment]
It ok
