### ISSUE TITLE
Separate section for Reverse Engineering

### ISSUE THREAD

**Issue by adhoc-king** [trimstray/the-book-of-secret-knowledge#49]
A separate section is needed for Reverse Engineering. Three popular tools which I can mention are [Hopper](https://www.hopperapp.com/), [IDA Pro](https://www.hex-rays.com/products/ida/) and [radare2](https://github.com/radare/radare2).

**Comment by trimstray** [comment]
Good point. Please add PR.

**Comment by adhoc-king** [comment]
#52

**Comment by trimstray** [comment]
Nice work, thanks! ([#52](https://github.com/trimstray/the-book-of-secret-knowledge/pull/52)).
