### ISSUE TITLE
Find faults to improve quality

### ISSUE THREAD

**Issue by trimstray** [trimstray/the-book-of-secret-knowledge#74]
- fix broken urls
- remove unusable items
- updated `CONTRIBUTING.md`

**Comment by jjesse** [comment]
seattle needs to be capitalized when talking about the Emerald Onion.

It is "seattle-based encrypted-transit internet service provider." and should be a simple "Seattle" change

**Comment by trimstray** [comment]
@jjesse : you're right, thanks

**Comment by trimstray** [comment]
#92
