### ISSUE TITLE
Unix Toolbox link down

### ISSUE THREAD

**Issue by breezykermo** [trimstray/the-book-of-secret-knowledge#8]
http://cb.vu/unixtoolbox.xhtml/ in line 329 of README ('Unix Toolbox') returns a server error.

Here's a snapshot from the wayback machine, dec 6th that has the goods:
https://web.archive.org/web/20181206192151/http://cb.vu/unixtoolbox.xhtml/

**Comment by trimstray** [comment]
Hi! Thanks for issue, I found correct url: `http://cb.vu/unixtoolbox.xhtml` - without last `/`.

Commit: 6de93f7
