### ISSUE TITLE
Add an awesome Podcast

### ISSUE THREAD

**Issue by 0xInfection** [trimstray/the-book-of-secret-knowledge#91]
Hi @trimstray, thanks for this fantastic work. Meanwhile here is an awesome OSINT podcast that I regularly follow (and ofc anyone interested in OSINT should too). I think its worthy of being under the Geeky Podcasts section. :)

https://twitter.com/WebBreacher/status/1100945773452128256

**Comment by trimstray** [comment]
Hi @0xInfection!

Wow it's really nice resource. I added this to Podcasts chapter.

Thanks a lot :+1:
